import os
import hydra
from omegaconf import DictConfig, OmegaConf
import torch
import numpy as np
import logging

from src.data.datamodule import CoastalDataModule
from src.models.factory import SegmentationModelFactory

logger = logging.getLogger(__name__)

@hydra.main(version_base="1.3", config_path="../configs", config_name="config")
def main(cfg: DictConfig):
    device = torch.device(cfg.device if torch.cuda.is_available() else "cpu")
    
    ckpt_path = os.path.join(cfg.output_dir, "best_model.pth")
    if not os.path.exists(ckpt_path):
        import shutil
        print(f"Target checkpoint path '{ckpt_path}' was not found.")
        print("Please point cfg.output_dir to a valid output log dir generated by train.py.")
        return
        
    datamodule = CoastalDataModule(
        root_dir=cfg.data.memmap_root,
        H=cfg.data.H, W=cfg.data.W,
        batch_size=cfg.data.val_batch_size,
        val_batch_size=cfg.data.val_batch_size,
        num_workers=cfg.data.num_workers,
        augment=False
    )
    datamodule.setup()
    
    test_dl = datamodule.test_dataloader()
    if test_dl is None:
        logger.warning("No test dataloader found, using val dataloader")
        test_dl = datamodule.val_dataloader()
    
    _encoder_kwargs = cfg.model.get("encoder_kwargs", None)
    _encoder_kwargs = OmegaConf.to_container(_encoder_kwargs, resolve=True) if _encoder_kwargs else {}
    model = SegmentationModelFactory.build(
        arch=cfg.model.arch,
        encoder_name=cfg.model.encoder_name,
        encoder_weights=cfg.model.encoder_weights,
        in_channels=cfg.model.in_channels,
        classes=cfg.model.num_classes,
        **_encoder_kwargs,
    )
    
    ckpt = torch.load(ckpt_path, map_location=device)
    model.load_state_dict(ckpt["model_state_dict"])
    model.to(device)
    model.eval()
    
    predict_output_dir = os.path.join(cfg.output_dir, "predictions")
    os.makedirs(predict_output_dir, exist_ok=True)
    
    sample_idx = 0
    with torch.no_grad():
        for batch in test_dl:
            x = batch["pixel_values"].to(device, non_blocking=True)
            y = batch["labels"].numpy()
            
            with torch.autocast(device_type=device.type, enabled=cfg.trainer.mixed_precision):
                logits = model(x)
                
            preds = torch.argmax(logits, dim=1).cpu().numpy().astype(np.uint8)
            x_np = x.cpu().numpy()
            
            for i in range(x_np.shape[0]):
                np.save(os.path.join(predict_output_dir, f"sample_{sample_idx:04d}_input.npy"), x_np[i])
                np.save(os.path.join(predict_output_dir, f"sample_{sample_idx:04d}_pred.npy"), preds[i])
                np.save(os.path.join(predict_output_dir, f"sample_{sample_idx:04d}_label.npy"), y[i])
                sample_idx += 1
                
    datamodule.teardown()
    print(f"Saved {sample_idx} input/pred/label triplets to '{predict_output_dir}'")

if __name__ == "__main__":
    main()
